/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ../include/gdalconst.i

package constant

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


extern void _wrap_Swig_free_constant_105d933e91f88a79(uintptr_t arg1);
extern swig_intgo _wrap_GDT_Unknown_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GDT_Byte_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GDT_UInt16_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GDT_Int16_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GDT_UInt32_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GDT_Int32_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GDT_Float32_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GDT_Float64_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GDT_CInt16_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GDT_CInt32_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GDT_CFloat32_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GDT_CFloat64_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GDT_TypeCount_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GA_ReadOnly_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GA_Update_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GF_Read_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GF_Write_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GRIORA_NearestNeighbour_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GRIORA_Bilinear_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GRIORA_Cubic_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GRIORA_CubicSpline_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GRIORA_Lanczos_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GRIORA_Average_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GRIORA_Mode_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GRIORA_Gauss_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GCI_Undefined_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GCI_GrayIndex_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GCI_PaletteIndex_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GCI_RedBand_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GCI_GreenBand_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GCI_BlueBand_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GCI_AlphaBand_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GCI_HueBand_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GCI_SaturationBand_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GCI_LightnessBand_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GCI_CyanBand_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GCI_MagentaBand_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GCI_YellowBand_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GCI_BlackBand_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GCI_YCbCr_YBand_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GCI_YCbCr_CrBand_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GCI_YCbCr_CbBand_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GRA_NearestNeighbour_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GRA_Bilinear_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GRA_Cubic_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GRA_CubicSpline_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GRA_Lanczos_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GRA_Average_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GRA_Mode_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GPI_Gray_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GPI_RGB_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GPI_CMYK_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GPI_HLS_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_CXT_Element_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_CXT_Text_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_CXT_Attribute_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_CXT_Comment_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_CXT_Literal_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_CE_None_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_CE_Debug_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_CE_Warning_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_CE_Failure_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_CE_Fatal_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_CPLE_None_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_CPLE_AppDefined_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_CPLE_OutOfMemory_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_CPLE_FileIO_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_CPLE_OpenFailed_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_CPLE_IllegalArg_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_CPLE_NotSupported_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_CPLE_AssertionFailed_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_CPLE_NoWriteAccess_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_CPLE_UserInterrupt_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_OF_ALL_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_OF_RASTER_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_OF_VECTOR_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_OF_GNM_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_OF_READONLY_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_OF_UPDATE_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_OF_SHARED_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_OF_VERBOSE_ERROR_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_CPLES_BackslashQuotable_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_CPLES_XML_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_CPLES_URL_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_CPLES_SQL_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_CPLES_CSV_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GFT_Integer_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GFT_Real_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GFT_String_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GFU_Generic_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GFU_PixelCount_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GFU_Name_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GFU_Min_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GFU_Max_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GFU_MinMax_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GFU_Red_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GFU_Green_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GFU_Blue_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GFU_Alpha_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GFU_RedMin_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GFU_GreenMin_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GFU_BlueMin_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GFU_AlphaMin_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GFU_RedMax_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GFU_GreenMax_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GFU_BlueMax_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GFU_AlphaMax_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GFU_MaxCount_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GARIO_PENDING_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GARIO_UPDATE_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GARIO_ERROR_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GARIO_COMPLETE_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GTO_TIP_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GTO_BIT_constant_105d933e91f88a79(void);
extern swig_intgo _wrap_GTO_BSQ_constant_105d933e91f88a79(void);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_constant_105d933e91f88a79(C.uintptr_t(_swig_i_0))
}

func _swig_getGDT_Unknown() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GDT_Unknown_constant_105d933e91f88a79())
	return swig_r
}

var GDT_Unknown int = _swig_getGDT_Unknown()
func _swig_getGDT_Byte() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GDT_Byte_constant_105d933e91f88a79())
	return swig_r
}

var GDT_Byte int = _swig_getGDT_Byte()
func _swig_getGDT_UInt16() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GDT_UInt16_constant_105d933e91f88a79())
	return swig_r
}

var GDT_UInt16 int = _swig_getGDT_UInt16()
func _swig_getGDT_Int16() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GDT_Int16_constant_105d933e91f88a79())
	return swig_r
}

var GDT_Int16 int = _swig_getGDT_Int16()
func _swig_getGDT_UInt32() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GDT_UInt32_constant_105d933e91f88a79())
	return swig_r
}

var GDT_UInt32 int = _swig_getGDT_UInt32()
func _swig_getGDT_Int32() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GDT_Int32_constant_105d933e91f88a79())
	return swig_r
}

var GDT_Int32 int = _swig_getGDT_Int32()
func _swig_getGDT_Float32() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GDT_Float32_constant_105d933e91f88a79())
	return swig_r
}

var GDT_Float32 int = _swig_getGDT_Float32()
func _swig_getGDT_Float64() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GDT_Float64_constant_105d933e91f88a79())
	return swig_r
}

var GDT_Float64 int = _swig_getGDT_Float64()
func _swig_getGDT_CInt16() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GDT_CInt16_constant_105d933e91f88a79())
	return swig_r
}

var GDT_CInt16 int = _swig_getGDT_CInt16()
func _swig_getGDT_CInt32() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GDT_CInt32_constant_105d933e91f88a79())
	return swig_r
}

var GDT_CInt32 int = _swig_getGDT_CInt32()
func _swig_getGDT_CFloat32() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GDT_CFloat32_constant_105d933e91f88a79())
	return swig_r
}

var GDT_CFloat32 int = _swig_getGDT_CFloat32()
func _swig_getGDT_CFloat64() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GDT_CFloat64_constant_105d933e91f88a79())
	return swig_r
}

var GDT_CFloat64 int = _swig_getGDT_CFloat64()
func _swig_getGDT_TypeCount() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GDT_TypeCount_constant_105d933e91f88a79())
	return swig_r
}

var GDT_TypeCount int = _swig_getGDT_TypeCount()
func _swig_getGA_ReadOnly() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GA_ReadOnly_constant_105d933e91f88a79())
	return swig_r
}

var GA_ReadOnly int = _swig_getGA_ReadOnly()
func _swig_getGA_Update() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GA_Update_constant_105d933e91f88a79())
	return swig_r
}

var GA_Update int = _swig_getGA_Update()
func _swig_getGF_Read() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GF_Read_constant_105d933e91f88a79())
	return swig_r
}

var GF_Read int = _swig_getGF_Read()
func _swig_getGF_Write() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GF_Write_constant_105d933e91f88a79())
	return swig_r
}

var GF_Write int = _swig_getGF_Write()
func _swig_getGRIORA_NearestNeighbour() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GRIORA_NearestNeighbour_constant_105d933e91f88a79())
	return swig_r
}

var GRIORA_NearestNeighbour int = _swig_getGRIORA_NearestNeighbour()
func _swig_getGRIORA_Bilinear() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GRIORA_Bilinear_constant_105d933e91f88a79())
	return swig_r
}

var GRIORA_Bilinear int = _swig_getGRIORA_Bilinear()
func _swig_getGRIORA_Cubic() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GRIORA_Cubic_constant_105d933e91f88a79())
	return swig_r
}

var GRIORA_Cubic int = _swig_getGRIORA_Cubic()
func _swig_getGRIORA_CubicSpline() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GRIORA_CubicSpline_constant_105d933e91f88a79())
	return swig_r
}

var GRIORA_CubicSpline int = _swig_getGRIORA_CubicSpline()
func _swig_getGRIORA_Lanczos() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GRIORA_Lanczos_constant_105d933e91f88a79())
	return swig_r
}

var GRIORA_Lanczos int = _swig_getGRIORA_Lanczos()
func _swig_getGRIORA_Average() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GRIORA_Average_constant_105d933e91f88a79())
	return swig_r
}

var GRIORA_Average int = _swig_getGRIORA_Average()
func _swig_getGRIORA_Mode() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GRIORA_Mode_constant_105d933e91f88a79())
	return swig_r
}

var GRIORA_Mode int = _swig_getGRIORA_Mode()
func _swig_getGRIORA_Gauss() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GRIORA_Gauss_constant_105d933e91f88a79())
	return swig_r
}

var GRIORA_Gauss int = _swig_getGRIORA_Gauss()
func _swig_getGCI_Undefined() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GCI_Undefined_constant_105d933e91f88a79())
	return swig_r
}

var GCI_Undefined int = _swig_getGCI_Undefined()
func _swig_getGCI_GrayIndex() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GCI_GrayIndex_constant_105d933e91f88a79())
	return swig_r
}

var GCI_GrayIndex int = _swig_getGCI_GrayIndex()
func _swig_getGCI_PaletteIndex() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GCI_PaletteIndex_constant_105d933e91f88a79())
	return swig_r
}

var GCI_PaletteIndex int = _swig_getGCI_PaletteIndex()
func _swig_getGCI_RedBand() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GCI_RedBand_constant_105d933e91f88a79())
	return swig_r
}

var GCI_RedBand int = _swig_getGCI_RedBand()
func _swig_getGCI_GreenBand() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GCI_GreenBand_constant_105d933e91f88a79())
	return swig_r
}

var GCI_GreenBand int = _swig_getGCI_GreenBand()
func _swig_getGCI_BlueBand() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GCI_BlueBand_constant_105d933e91f88a79())
	return swig_r
}

var GCI_BlueBand int = _swig_getGCI_BlueBand()
func _swig_getGCI_AlphaBand() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GCI_AlphaBand_constant_105d933e91f88a79())
	return swig_r
}

var GCI_AlphaBand int = _swig_getGCI_AlphaBand()
func _swig_getGCI_HueBand() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GCI_HueBand_constant_105d933e91f88a79())
	return swig_r
}

var GCI_HueBand int = _swig_getGCI_HueBand()
func _swig_getGCI_SaturationBand() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GCI_SaturationBand_constant_105d933e91f88a79())
	return swig_r
}

var GCI_SaturationBand int = _swig_getGCI_SaturationBand()
func _swig_getGCI_LightnessBand() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GCI_LightnessBand_constant_105d933e91f88a79())
	return swig_r
}

var GCI_LightnessBand int = _swig_getGCI_LightnessBand()
func _swig_getGCI_CyanBand() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GCI_CyanBand_constant_105d933e91f88a79())
	return swig_r
}

var GCI_CyanBand int = _swig_getGCI_CyanBand()
func _swig_getGCI_MagentaBand() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GCI_MagentaBand_constant_105d933e91f88a79())
	return swig_r
}

var GCI_MagentaBand int = _swig_getGCI_MagentaBand()
func _swig_getGCI_YellowBand() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GCI_YellowBand_constant_105d933e91f88a79())
	return swig_r
}

var GCI_YellowBand int = _swig_getGCI_YellowBand()
func _swig_getGCI_BlackBand() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GCI_BlackBand_constant_105d933e91f88a79())
	return swig_r
}

var GCI_BlackBand int = _swig_getGCI_BlackBand()
func _swig_getGCI_YCbCr_YBand() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GCI_YCbCr_YBand_constant_105d933e91f88a79())
	return swig_r
}

var GCI_YCbCr_YBand int = _swig_getGCI_YCbCr_YBand()
func _swig_getGCI_YCbCr_CrBand() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GCI_YCbCr_CrBand_constant_105d933e91f88a79())
	return swig_r
}

var GCI_YCbCr_CrBand int = _swig_getGCI_YCbCr_CrBand()
func _swig_getGCI_YCbCr_CbBand() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GCI_YCbCr_CbBand_constant_105d933e91f88a79())
	return swig_r
}

var GCI_YCbCr_CbBand int = _swig_getGCI_YCbCr_CbBand()
func _swig_getGRA_NearestNeighbour() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GRA_NearestNeighbour_constant_105d933e91f88a79())
	return swig_r
}

var GRA_NearestNeighbour int = _swig_getGRA_NearestNeighbour()
func _swig_getGRA_Bilinear() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GRA_Bilinear_constant_105d933e91f88a79())
	return swig_r
}

var GRA_Bilinear int = _swig_getGRA_Bilinear()
func _swig_getGRA_Cubic() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GRA_Cubic_constant_105d933e91f88a79())
	return swig_r
}

var GRA_Cubic int = _swig_getGRA_Cubic()
func _swig_getGRA_CubicSpline() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GRA_CubicSpline_constant_105d933e91f88a79())
	return swig_r
}

var GRA_CubicSpline int = _swig_getGRA_CubicSpline()
func _swig_getGRA_Lanczos() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GRA_Lanczos_constant_105d933e91f88a79())
	return swig_r
}

var GRA_Lanczos int = _swig_getGRA_Lanczos()
func _swig_getGRA_Average() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GRA_Average_constant_105d933e91f88a79())
	return swig_r
}

var GRA_Average int = _swig_getGRA_Average()
func _swig_getGRA_Mode() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GRA_Mode_constant_105d933e91f88a79())
	return swig_r
}

var GRA_Mode int = _swig_getGRA_Mode()
func _swig_getGPI_Gray() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GPI_Gray_constant_105d933e91f88a79())
	return swig_r
}

var GPI_Gray int = _swig_getGPI_Gray()
func _swig_getGPI_RGB() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GPI_RGB_constant_105d933e91f88a79())
	return swig_r
}

var GPI_RGB int = _swig_getGPI_RGB()
func _swig_getGPI_CMYK() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GPI_CMYK_constant_105d933e91f88a79())
	return swig_r
}

var GPI_CMYK int = _swig_getGPI_CMYK()
func _swig_getGPI_HLS() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GPI_HLS_constant_105d933e91f88a79())
	return swig_r
}

var GPI_HLS int = _swig_getGPI_HLS()
func _swig_getCXT_Element() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_CXT_Element_constant_105d933e91f88a79())
	return swig_r
}

var CXT_Element int = _swig_getCXT_Element()
func _swig_getCXT_Text() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_CXT_Text_constant_105d933e91f88a79())
	return swig_r
}

var CXT_Text int = _swig_getCXT_Text()
func _swig_getCXT_Attribute() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_CXT_Attribute_constant_105d933e91f88a79())
	return swig_r
}

var CXT_Attribute int = _swig_getCXT_Attribute()
func _swig_getCXT_Comment() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_CXT_Comment_constant_105d933e91f88a79())
	return swig_r
}

var CXT_Comment int = _swig_getCXT_Comment()
func _swig_getCXT_Literal() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_CXT_Literal_constant_105d933e91f88a79())
	return swig_r
}

var CXT_Literal int = _swig_getCXT_Literal()
func _swig_getCE_None() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_CE_None_constant_105d933e91f88a79())
	return swig_r
}

var CE_None int = _swig_getCE_None()
func _swig_getCE_Debug() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_CE_Debug_constant_105d933e91f88a79())
	return swig_r
}

var CE_Debug int = _swig_getCE_Debug()
func _swig_getCE_Warning() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_CE_Warning_constant_105d933e91f88a79())
	return swig_r
}

var CE_Warning int = _swig_getCE_Warning()
func _swig_getCE_Failure() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_CE_Failure_constant_105d933e91f88a79())
	return swig_r
}

var CE_Failure int = _swig_getCE_Failure()
func _swig_getCE_Fatal() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_CE_Fatal_constant_105d933e91f88a79())
	return swig_r
}

var CE_Fatal int = _swig_getCE_Fatal()
func _swig_getCPLE_None() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_CPLE_None_constant_105d933e91f88a79())
	return swig_r
}

var CPLE_None int = _swig_getCPLE_None()
func _swig_getCPLE_AppDefined() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_CPLE_AppDefined_constant_105d933e91f88a79())
	return swig_r
}

var CPLE_AppDefined int = _swig_getCPLE_AppDefined()
func _swig_getCPLE_OutOfMemory() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_CPLE_OutOfMemory_constant_105d933e91f88a79())
	return swig_r
}

var CPLE_OutOfMemory int = _swig_getCPLE_OutOfMemory()
func _swig_getCPLE_FileIO() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_CPLE_FileIO_constant_105d933e91f88a79())
	return swig_r
}

var CPLE_FileIO int = _swig_getCPLE_FileIO()
func _swig_getCPLE_OpenFailed() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_CPLE_OpenFailed_constant_105d933e91f88a79())
	return swig_r
}

var CPLE_OpenFailed int = _swig_getCPLE_OpenFailed()
func _swig_getCPLE_IllegalArg() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_CPLE_IllegalArg_constant_105d933e91f88a79())
	return swig_r
}

var CPLE_IllegalArg int = _swig_getCPLE_IllegalArg()
func _swig_getCPLE_NotSupported() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_CPLE_NotSupported_constant_105d933e91f88a79())
	return swig_r
}

var CPLE_NotSupported int = _swig_getCPLE_NotSupported()
func _swig_getCPLE_AssertionFailed() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_CPLE_AssertionFailed_constant_105d933e91f88a79())
	return swig_r
}

var CPLE_AssertionFailed int = _swig_getCPLE_AssertionFailed()
func _swig_getCPLE_NoWriteAccess() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_CPLE_NoWriteAccess_constant_105d933e91f88a79())
	return swig_r
}

var CPLE_NoWriteAccess int = _swig_getCPLE_NoWriteAccess()
func _swig_getCPLE_UserInterrupt() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_CPLE_UserInterrupt_constant_105d933e91f88a79())
	return swig_r
}

var CPLE_UserInterrupt int = _swig_getCPLE_UserInterrupt()
func _swig_getOF_ALL() (_swig_ret uint) {
	var swig_r uint
	swig_r = (uint)(C._wrap_OF_ALL_constant_105d933e91f88a79())
	return swig_r
}

var OF_ALL uint = _swig_getOF_ALL()
func _swig_getOF_RASTER() (_swig_ret uint) {
	var swig_r uint
	swig_r = (uint)(C._wrap_OF_RASTER_constant_105d933e91f88a79())
	return swig_r
}

var OF_RASTER uint = _swig_getOF_RASTER()
func _swig_getOF_VECTOR() (_swig_ret uint) {
	var swig_r uint
	swig_r = (uint)(C._wrap_OF_VECTOR_constant_105d933e91f88a79())
	return swig_r
}

var OF_VECTOR uint = _swig_getOF_VECTOR()
func _swig_getOF_GNM() (_swig_ret uint) {
	var swig_r uint
	swig_r = (uint)(C._wrap_OF_GNM_constant_105d933e91f88a79())
	return swig_r
}

var OF_GNM uint = _swig_getOF_GNM()
func _swig_getOF_READONLY() (_swig_ret uint) {
	var swig_r uint
	swig_r = (uint)(C._wrap_OF_READONLY_constant_105d933e91f88a79())
	return swig_r
}

var OF_READONLY uint = _swig_getOF_READONLY()
func _swig_getOF_UPDATE() (_swig_ret uint) {
	var swig_r uint
	swig_r = (uint)(C._wrap_OF_UPDATE_constant_105d933e91f88a79())
	return swig_r
}

var OF_UPDATE uint = _swig_getOF_UPDATE()
func _swig_getOF_SHARED() (_swig_ret uint) {
	var swig_r uint
	swig_r = (uint)(C._wrap_OF_SHARED_constant_105d933e91f88a79())
	return swig_r
}

var OF_SHARED uint = _swig_getOF_SHARED()
func _swig_getOF_VERBOSE_ERROR() (_swig_ret uint) {
	var swig_r uint
	swig_r = (uint)(C._wrap_OF_VERBOSE_ERROR_constant_105d933e91f88a79())
	return swig_r
}

var OF_VERBOSE_ERROR uint = _swig_getOF_VERBOSE_ERROR()
const DMD_LONGNAME string = "GDAL_DMD_LONGNAME"
const DMD_HELPTOPIC string = "GDAL_DMD_HELPTOPIC"
const DMD_MIMETYPE string = "GDAL_DMD_MIMETYPE"
const DMD_EXTENSION string = "GDAL_DMD_EXTENSION"
const DMD_EXTENSIONS string = "GDAL_DMD_EXTENSIONS"
const DMD_CONNECTION_PREFIX string = "GDAL_DMD_CONNECTION_PREFIX"
const DMD_CREATIONOPTIONLIST string = "GDAL_DMD_CREATIONOPTIONLIST"
const DMD_CREATIONDATATYPES string = "GDAL_DMD_CREATIONDATATYPES"
const DMD_CREATIONFIELDDATATYPES string = "GDAL_DMD_CREATIONFIELDDATATYPES"
const DMD_SUBDATASETS string = "GDAL_DMD_SUBDATASETS"
const DCAP_OPEN string = "GDAL_DCAP_OPEN"
const DCAP_CREATE string = "GDAL_DCAP_CREATE"
const DCAP_CREATECOPY string = "GDAL_DCAP_CREATECOPY"
const DCAP_VIRTUALIO string = "GDAL_DCAP_VIRTUALIO"
const DCAP_RASTER string = "GDAL_DCAP_RASTER"
const DCAP_VECTOR string = "GDAL_DCAP_VECTOR"
const DCAP_NOTNULL_FIELDS string = "GDAL_DCAP_NOTNULL_FIELDS"
const DCAP_DEFAULT_FIELDS string = "GDAL_DCAP_DEFAULT_FIELDS"
const DCAP_NOTNULL_GEOMFIELDS string = "GDAL_DCAP_NOTNULL_GEOMFIELDS"
func _swig_getCPLES_BackslashQuotable() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_CPLES_BackslashQuotable_constant_105d933e91f88a79())
	return swig_r
}

var CPLES_BackslashQuotable int = _swig_getCPLES_BackslashQuotable()
func _swig_getCPLES_XML() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_CPLES_XML_constant_105d933e91f88a79())
	return swig_r
}

var CPLES_XML int = _swig_getCPLES_XML()
func _swig_getCPLES_URL() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_CPLES_URL_constant_105d933e91f88a79())
	return swig_r
}

var CPLES_URL int = _swig_getCPLES_URL()
func _swig_getCPLES_SQL() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_CPLES_SQL_constant_105d933e91f88a79())
	return swig_r
}

var CPLES_SQL int = _swig_getCPLES_SQL()
func _swig_getCPLES_CSV() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_CPLES_CSV_constant_105d933e91f88a79())
	return swig_r
}

var CPLES_CSV int = _swig_getCPLES_CSV()
func _swig_getGFT_Integer() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GFT_Integer_constant_105d933e91f88a79())
	return swig_r
}

var GFT_Integer int = _swig_getGFT_Integer()
func _swig_getGFT_Real() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GFT_Real_constant_105d933e91f88a79())
	return swig_r
}

var GFT_Real int = _swig_getGFT_Real()
func _swig_getGFT_String() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GFT_String_constant_105d933e91f88a79())
	return swig_r
}

var GFT_String int = _swig_getGFT_String()
func _swig_getGFU_Generic() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GFU_Generic_constant_105d933e91f88a79())
	return swig_r
}

var GFU_Generic int = _swig_getGFU_Generic()
func _swig_getGFU_PixelCount() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GFU_PixelCount_constant_105d933e91f88a79())
	return swig_r
}

var GFU_PixelCount int = _swig_getGFU_PixelCount()
func _swig_getGFU_Name() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GFU_Name_constant_105d933e91f88a79())
	return swig_r
}

var GFU_Name int = _swig_getGFU_Name()
func _swig_getGFU_Min() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GFU_Min_constant_105d933e91f88a79())
	return swig_r
}

var GFU_Min int = _swig_getGFU_Min()
func _swig_getGFU_Max() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GFU_Max_constant_105d933e91f88a79())
	return swig_r
}

var GFU_Max int = _swig_getGFU_Max()
func _swig_getGFU_MinMax() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GFU_MinMax_constant_105d933e91f88a79())
	return swig_r
}

var GFU_MinMax int = _swig_getGFU_MinMax()
func _swig_getGFU_Red() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GFU_Red_constant_105d933e91f88a79())
	return swig_r
}

var GFU_Red int = _swig_getGFU_Red()
func _swig_getGFU_Green() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GFU_Green_constant_105d933e91f88a79())
	return swig_r
}

var GFU_Green int = _swig_getGFU_Green()
func _swig_getGFU_Blue() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GFU_Blue_constant_105d933e91f88a79())
	return swig_r
}

var GFU_Blue int = _swig_getGFU_Blue()
func _swig_getGFU_Alpha() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GFU_Alpha_constant_105d933e91f88a79())
	return swig_r
}

var GFU_Alpha int = _swig_getGFU_Alpha()
func _swig_getGFU_RedMin() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GFU_RedMin_constant_105d933e91f88a79())
	return swig_r
}

var GFU_RedMin int = _swig_getGFU_RedMin()
func _swig_getGFU_GreenMin() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GFU_GreenMin_constant_105d933e91f88a79())
	return swig_r
}

var GFU_GreenMin int = _swig_getGFU_GreenMin()
func _swig_getGFU_BlueMin() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GFU_BlueMin_constant_105d933e91f88a79())
	return swig_r
}

var GFU_BlueMin int = _swig_getGFU_BlueMin()
func _swig_getGFU_AlphaMin() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GFU_AlphaMin_constant_105d933e91f88a79())
	return swig_r
}

var GFU_AlphaMin int = _swig_getGFU_AlphaMin()
func _swig_getGFU_RedMax() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GFU_RedMax_constant_105d933e91f88a79())
	return swig_r
}

var GFU_RedMax int = _swig_getGFU_RedMax()
func _swig_getGFU_GreenMax() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GFU_GreenMax_constant_105d933e91f88a79())
	return swig_r
}

var GFU_GreenMax int = _swig_getGFU_GreenMax()
func _swig_getGFU_BlueMax() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GFU_BlueMax_constant_105d933e91f88a79())
	return swig_r
}

var GFU_BlueMax int = _swig_getGFU_BlueMax()
func _swig_getGFU_AlphaMax() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GFU_AlphaMax_constant_105d933e91f88a79())
	return swig_r
}

var GFU_AlphaMax int = _swig_getGFU_AlphaMax()
func _swig_getGFU_MaxCount() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GFU_MaxCount_constant_105d933e91f88a79())
	return swig_r
}

var GFU_MaxCount int = _swig_getGFU_MaxCount()
const GMF_ALL_VALID int = 0x01
const GMF_PER_DATASET int = 0x02
const GMF_ALPHA int = 0x04
const GMF_NODATA int = 0x08
func _swig_getGARIO_PENDING() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GARIO_PENDING_constant_105d933e91f88a79())
	return swig_r
}

var GARIO_PENDING int = _swig_getGARIO_PENDING()
func _swig_getGARIO_UPDATE() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GARIO_UPDATE_constant_105d933e91f88a79())
	return swig_r
}

var GARIO_UPDATE int = _swig_getGARIO_UPDATE()
func _swig_getGARIO_ERROR() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GARIO_ERROR_constant_105d933e91f88a79())
	return swig_r
}

var GARIO_ERROR int = _swig_getGARIO_ERROR()
func _swig_getGARIO_COMPLETE() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GARIO_COMPLETE_constant_105d933e91f88a79())
	return swig_r
}

var GARIO_COMPLETE int = _swig_getGARIO_COMPLETE()
func _swig_getGTO_TIP() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GTO_TIP_constant_105d933e91f88a79())
	return swig_r
}

var GTO_TIP int = _swig_getGTO_TIP()
func _swig_getGTO_BIT() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GTO_BIT_constant_105d933e91f88a79())
	return swig_r
}

var GTO_BIT int = _swig_getGTO_BIT()
func _swig_getGTO_BSQ() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_GTO_BSQ_constant_105d933e91f88a79())
	return swig_r
}

var GTO_BSQ int = _swig_getGTO_BSQ()

