/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ../include/osr.i

package osr

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;
typedef _gostring_ swig_type_3;
typedef _gostring_ swig_type_4;
typedef _gostring_ swig_type_5;
typedef _gostring_ swig_type_6;
typedef _gostring_ swig_type_7;
typedef _gostring_ swig_type_8;
typedef _gostring_ swig_type_9;
typedef _gostring_ swig_type_10;
typedef _gostring_ swig_type_11;
typedef _gostring_ swig_type_12;
typedef _gostring_ swig_type_13;
typedef _gostring_ swig_type_14;
typedef _gostring_ swig_type_15;
typedef _gostring_ swig_type_16;
typedef _gostring_ swig_type_17;
typedef _gostring_ swig_type_18;
typedef _gostring_ swig_type_19;
typedef _gostring_ swig_type_20;
typedef _gostring_ swig_type_21;
typedef _gostring_ swig_type_22;
typedef _gostring_ swig_type_23;
typedef _gostring_ swig_type_24;
typedef _gostring_ swig_type_25;
typedef _gostring_ swig_type_26;
typedef _gostring_ swig_type_27;
typedef _gostring_ swig_type_28;
typedef _gostring_ swig_type_29;
typedef _gostring_ swig_type_30;
typedef _gostring_ swig_type_31;
typedef _gostring_ swig_type_32;
typedef _gostring_ swig_type_33;
typedef _gostring_ swig_type_34;
typedef _gostring_ swig_type_35;
typedef _gostring_ swig_type_36;
typedef _gostring_ swig_type_37;
typedef _gostring_ swig_type_38;
typedef _gostring_ swig_type_39;
typedef _gostring_ swig_type_40;
typedef _gostring_ swig_type_41;
typedef _gostring_ swig_type_42;
typedef _gostring_ swig_type_43;
typedef _gostring_ swig_type_44;
typedef _gostring_ swig_type_45;
typedef _gostring_ swig_type_46;
typedef _gostring_ swig_type_47;
typedef _gostring_ swig_type_48;
typedef long long swig_type_49;
typedef long long swig_type_50;
typedef long long swig_type_51;
typedef _gostring_ swig_type_52;
typedef _gostring_ swig_type_53;
typedef _gostring_ swig_type_54;
typedef _gostring_ swig_type_55;
typedef _gostring_ swig_type_56;
typedef _gostring_ swig_type_57;
extern void _wrap_Swig_free_osr_09662cf3c15b8b8e(uintptr_t arg1);
extern swig_type_1 _wrap_SRS_WKT_WGS84_osr_09662cf3c15b8b8e(void);

// "cpl_string.h" is needed to declare CSLDestroy.
#include "cpl_string.h"

// We need to link against GDAL when building the Go module.
#cgo LDFLAGS: -lgdal

extern swig_intgo _wrap_GetWellKnownGeogCSAsWKT_osr_09662cf3c15b8b8e(swig_type_2 arg1, swig_voidp arg2);
extern swig_intgo _wrap_GetUserInputAsWKT_osr_09662cf3c15b8b8e(swig_type_3 arg1, swig_voidp arg2);
extern swig_voidp _wrap_GetProjectionMethods_osr_09662cf3c15b8b8e(void);
extern swig_voidp _wrap_GetProjectionMethodParameterList_osr_09662cf3c15b8b8e(swig_type_4 arg1, swig_voidp arg2);
extern void _wrap_GetProjectionMethodParamInfo_osr_09662cf3c15b8b8e(swig_type_5 arg1, swig_type_6 arg2, swig_voidp arg3, swig_voidp arg4, swig_voidp arg5);
extern uintptr_t _wrap_new_SpatialReference_osr_09662cf3c15b8b8e(intgo _swig_args, swig_type_7 arg1);
extern void _wrap_delete_SpatialReference_osr_09662cf3c15b8b8e(uintptr_t arg1);
extern swig_type_8 _wrap_SpatialReference___str___osr_09662cf3c15b8b8e(uintptr_t arg1);
extern swig_intgo _wrap_SpatialReference_IsSame_osr_09662cf3c15b8b8e(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_SpatialReference_IsSameGeogCS_osr_09662cf3c15b8b8e(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_SpatialReference_IsSameVertCS_osr_09662cf3c15b8b8e(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_SpatialReference_IsGeographic_osr_09662cf3c15b8b8e(uintptr_t arg1);
extern swig_intgo _wrap_SpatialReference_IsProjected_osr_09662cf3c15b8b8e(uintptr_t arg1);
extern swig_intgo _wrap_SpatialReference_IsCompound_osr_09662cf3c15b8b8e(uintptr_t arg1);
extern swig_intgo _wrap_SpatialReference_IsGeocentric_osr_09662cf3c15b8b8e(uintptr_t arg1);
extern swig_intgo _wrap_SpatialReference_IsLocal_osr_09662cf3c15b8b8e(uintptr_t arg1);
extern swig_intgo _wrap_SpatialReference_IsVertical_osr_09662cf3c15b8b8e(uintptr_t arg1);
extern swig_intgo _wrap_SpatialReference_EPSGTreatsAsLatLong_osr_09662cf3c15b8b8e(uintptr_t arg1);
extern swig_intgo _wrap_SpatialReference_EPSGTreatsAsNorthingEasting_osr_09662cf3c15b8b8e(uintptr_t arg1);
extern swig_intgo _wrap_SpatialReference_SetAuthority_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_type_9 arg2, swig_type_10 arg3, swig_intgo arg4);
extern swig_type_11 _wrap_SpatialReference_GetAttrValue_osr_09662cf3c15b8b8e(intgo _swig_args, uintptr_t arg1, swig_type_12 arg2, swig_intgo arg3);
extern swig_intgo _wrap_SpatialReference_SetAttrValue_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_type_13 arg2, swig_type_14 arg3);
extern swig_intgo _wrap_SpatialReference_SetAngularUnits_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_type_15 arg2, double arg3);
extern double _wrap_SpatialReference_GetAngularUnits_osr_09662cf3c15b8b8e(uintptr_t arg1);
extern swig_intgo _wrap_SpatialReference_SetTargetLinearUnits_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_type_16 arg2, swig_type_17 arg3, double arg4);
extern swig_intgo _wrap_SpatialReference_SetLinearUnits_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_type_18 arg2, double arg3);
extern swig_intgo _wrap_SpatialReference_SetLinearUnitsAndUpdateParameters_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_type_19 arg2, double arg3);
extern double _wrap_SpatialReference_GetLinearUnits_osr_09662cf3c15b8b8e(uintptr_t arg1);
extern swig_type_20 _wrap_SpatialReference_GetLinearUnitsName_osr_09662cf3c15b8b8e(uintptr_t arg1);
extern swig_type_21 _wrap_SpatialReference_GetAuthorityCode_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_type_22 arg2);
extern swig_type_23 _wrap_SpatialReference_GetAuthorityName_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_type_24 arg2);
extern swig_intgo _wrap_SpatialReference_SetUTM_osr_09662cf3c15b8b8e(intgo _swig_args, uintptr_t arg1, swig_intgo arg2, swig_intgo arg3);
extern swig_intgo _wrap_SpatialReference_GetUTMZone_osr_09662cf3c15b8b8e(uintptr_t arg1);
extern swig_intgo _wrap_SpatialReference_SetStatePlane_osr_09662cf3c15b8b8e(intgo _swig_args, uintptr_t arg1, swig_intgo arg2, swig_intgo arg3, swig_type_25 arg4, double arg5);
extern swig_intgo _wrap_SpatialReference_AutoIdentifyEPSG_osr_09662cf3c15b8b8e(uintptr_t arg1);
extern swig_intgo _wrap_SpatialReference_SetProjection_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_type_26 arg2);
extern swig_intgo _wrap_SpatialReference_SetProjParm_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_type_27 arg2, double arg3);
extern double _wrap_SpatialReference_GetProjParm_osr_09662cf3c15b8b8e(intgo _swig_args, uintptr_t arg1, swig_type_28 arg2, double arg3);
extern swig_intgo _wrap_SpatialReference_SetNormProjParm_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_type_29 arg2, double arg3);
extern double _wrap_SpatialReference_GetNormProjParm_osr_09662cf3c15b8b8e(intgo _swig_args, uintptr_t arg1, swig_type_30 arg2, double arg3);
extern double _wrap_SpatialReference_GetSemiMajor_osr_09662cf3c15b8b8e(uintptr_t arg1);
extern double _wrap_SpatialReference_GetSemiMinor_osr_09662cf3c15b8b8e(uintptr_t arg1);
extern double _wrap_SpatialReference_GetInvFlattening_osr_09662cf3c15b8b8e(uintptr_t arg1);
extern swig_intgo _wrap_SpatialReference_SetACEA_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5, double arg6, double arg7);
extern swig_intgo _wrap_SpatialReference_SetAE_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5);
extern swig_intgo _wrap_SpatialReference_SetBonne_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5);
extern swig_intgo _wrap_SpatialReference_SetCEA_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5);
extern swig_intgo _wrap_SpatialReference_SetCS_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5);
extern swig_intgo _wrap_SpatialReference_SetEC_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5, double arg6, double arg7);
extern swig_intgo _wrap_SpatialReference_SetEckertIV_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4);
extern swig_intgo _wrap_SpatialReference_SetEckertVI_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4);
extern swig_intgo _wrap_SpatialReference_SetEquirectangular_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5);
extern swig_intgo _wrap_SpatialReference_SetEquirectangular2_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5, double arg6);
extern swig_intgo _wrap_SpatialReference_SetGaussSchreiberTMercator_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5, double arg6);
extern swig_intgo _wrap_SpatialReference_SetGS_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4);
extern swig_intgo _wrap_SpatialReference_SetGH_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4);
extern swig_intgo _wrap_SpatialReference_SetIGH_osr_09662cf3c15b8b8e(uintptr_t arg1);
extern swig_intgo _wrap_SpatialReference_SetGEOS_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5);
extern swig_intgo _wrap_SpatialReference_SetGnomonic_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5);
extern swig_intgo _wrap_SpatialReference_SetHOM_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5, double arg6, double arg7, double arg8);
extern swig_intgo _wrap_SpatialReference_SetHOM2PNO_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5, double arg6, double arg7, double arg8, double arg9);
extern swig_intgo _wrap_SpatialReference_SetKrovak_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5, double arg6, double arg7, double arg8);
extern swig_intgo _wrap_SpatialReference_SetLAEA_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5);
extern swig_intgo _wrap_SpatialReference_SetLCC_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5, double arg6, double arg7);
extern swig_intgo _wrap_SpatialReference_SetLCC1SP_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5, double arg6);
extern swig_intgo _wrap_SpatialReference_SetLCCB_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5, double arg6, double arg7);
extern swig_intgo _wrap_SpatialReference_SetMC_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5);
extern swig_intgo _wrap_SpatialReference_SetMercator_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5, double arg6);
extern swig_intgo _wrap_SpatialReference_SetMollweide_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4);
extern swig_intgo _wrap_SpatialReference_SetNZMG_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5);
extern swig_intgo _wrap_SpatialReference_SetOS_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5, double arg6);
extern swig_intgo _wrap_SpatialReference_SetOrthographic_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5);
extern swig_intgo _wrap_SpatialReference_SetPolyconic_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5);
extern swig_intgo _wrap_SpatialReference_SetPS_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5, double arg6);
extern swig_intgo _wrap_SpatialReference_SetRobinson_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4);
extern swig_intgo _wrap_SpatialReference_SetSinusoidal_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4);
extern swig_intgo _wrap_SpatialReference_SetStereographic_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5, double arg6);
extern swig_intgo _wrap_SpatialReference_SetSOC_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5);
extern swig_intgo _wrap_SpatialReference_SetTM_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5, double arg6);
extern swig_intgo _wrap_SpatialReference_SetTMVariant_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_type_31 arg2, double arg3, double arg4, double arg5, double arg6, double arg7);
extern swig_intgo _wrap_SpatialReference_SetTMG_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5);
extern swig_intgo _wrap_SpatialReference_SetTMSO_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4, double arg5, double arg6);
extern swig_intgo _wrap_SpatialReference_SetVDG_osr_09662cf3c15b8b8e(uintptr_t arg1, double arg2, double arg3, double arg4);
extern swig_intgo _wrap_SpatialReference_SetWellKnownGeogCS_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_type_32 arg2);
extern swig_intgo _wrap_SpatialReference_SetFromUserInput_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_type_33 arg2);
extern swig_intgo _wrap_SpatialReference_CopyGeogCSFrom_osr_09662cf3c15b8b8e(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_SpatialReference_SetTOWGS84_osr_09662cf3c15b8b8e(intgo _swig_args, uintptr_t arg1, double arg2, double arg3, double arg4, double arg5, double arg6, double arg7, double arg8);
extern swig_intgo _wrap_SpatialReference_GetTOWGS84_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_voidp arg2);
extern swig_intgo _wrap_SpatialReference_SetLocalCS_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_type_34 arg2);
extern swig_intgo _wrap_SpatialReference_SetGeogCS_osr_09662cf3c15b8b8e(intgo _swig_args, uintptr_t arg1, swig_type_35 arg2, swig_type_36 arg3, swig_type_37 arg4, double arg5, double arg6, swig_type_38 arg7, double arg8, swig_type_39 arg9, double arg10);
extern swig_intgo _wrap_SpatialReference_SetProjCS_osr_09662cf3c15b8b8e(intgo _swig_args, uintptr_t arg1, swig_type_40 arg2);
extern swig_intgo _wrap_SpatialReference_SetGeocCS_osr_09662cf3c15b8b8e(intgo _swig_args, uintptr_t arg1, swig_type_41 arg2);
extern swig_intgo _wrap_SpatialReference_SetVertCS_osr_09662cf3c15b8b8e(intgo _swig_args, uintptr_t arg1, swig_type_42 arg2, swig_type_43 arg3, swig_intgo arg4);
extern swig_intgo _wrap_SpatialReference_SetCompoundCS_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_type_44 arg2, uintptr_t arg3, uintptr_t arg4);
extern swig_intgo _wrap_SpatialReference_ImportFromWkt_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_voidp arg2);
extern swig_intgo _wrap_SpatialReference_ImportFromProj4_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_type_45 arg2);
extern swig_intgo _wrap_SpatialReference_ImportFromUrl_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_type_46 arg2);
extern swig_intgo _wrap_SpatialReference_ImportFromESRI_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_voidp arg2);
extern swig_intgo _wrap_SpatialReference_ImportFromEPSG_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_SpatialReference_ImportFromEPSGA_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_SpatialReference_ImportFromPCI_osr_09662cf3c15b8b8e(intgo _swig_args, uintptr_t arg1, swig_type_47 arg2, swig_type_48 arg3, swig_voidp arg4);
extern swig_intgo _wrap_SpatialReference_ImportFromUSGS_osr_09662cf3c15b8b8e(intgo _swig_args, uintptr_t arg1, swig_type_49 arg2, swig_type_50 arg3, swig_voidp arg4, swig_type_51 arg5);
extern swig_intgo _wrap_SpatialReference_ImportFromXML_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_type_52 arg2);
extern swig_intgo _wrap_SpatialReference_ImportFromERM_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_type_53 arg2, swig_type_54 arg3, swig_type_55 arg4);
extern swig_intgo _wrap_SpatialReference_ImportFromMICoordSys_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_type_56 arg2);
extern swig_intgo _wrap_SpatialReference_ImportFromOzi_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_voidp arg2);
extern swig_intgo _wrap_SpatialReference_ExportToWkt_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_voidp arg2);
extern swig_intgo _wrap_SpatialReference_ExportToPrettyWkt_osr_09662cf3c15b8b8e(intgo _swig_args, uintptr_t arg1, swig_voidp arg2, swig_intgo arg3);
extern swig_intgo _wrap_SpatialReference_ExportToProj4_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_voidp arg2);
extern swig_intgo _wrap_SpatialReference_ExportToPCI_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_voidp arg2, swig_voidp arg3, swig_voidp arg4);
extern swig_intgo _wrap_SpatialReference_ExportToUSGS_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_voidp arg2, swig_voidp arg3, swig_voidp arg4, swig_voidp arg5);
extern swig_intgo _wrap_SpatialReference_ExportToXML_osr_09662cf3c15b8b8e(intgo _swig_args, uintptr_t arg1, swig_voidp arg2, swig_type_57 arg3);
extern swig_intgo _wrap_SpatialReference_ExportToMICoordSys_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_voidp arg2);
extern uintptr_t _wrap_SpatialReference_CloneGeogCS_osr_09662cf3c15b8b8e(uintptr_t arg1);
extern uintptr_t _wrap_SpatialReference_Clone_osr_09662cf3c15b8b8e(uintptr_t arg1);
extern swig_intgo _wrap_SpatialReference_Validate_osr_09662cf3c15b8b8e(uintptr_t arg1);
extern swig_intgo _wrap_SpatialReference_StripCTParms_osr_09662cf3c15b8b8e(uintptr_t arg1);
extern swig_intgo _wrap_SpatialReference_FixupOrdering_osr_09662cf3c15b8b8e(uintptr_t arg1);
extern swig_intgo _wrap_SpatialReference_Fixup_osr_09662cf3c15b8b8e(uintptr_t arg1);
extern swig_intgo _wrap_SpatialReference_MorphToESRI_osr_09662cf3c15b8b8e(uintptr_t arg1);
extern swig_intgo _wrap_SpatialReference_MorphFromESRI_osr_09662cf3c15b8b8e(uintptr_t arg1);
extern uintptr_t _wrap_new_CoordinateTransformation_osr_09662cf3c15b8b8e(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_delete_CoordinateTransformation_osr_09662cf3c15b8b8e(uintptr_t arg1);
extern void _wrap_CoordinateTransformation_TransformPoint__SWIG_0_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_voidp arg2);
extern void _wrap_CoordinateTransformation_TransformPoint__SWIG_1_osr_09662cf3c15b8b8e(intgo _swig_args, uintptr_t arg1, swig_voidp arg2, double arg3, double arg4, double arg5);
extern void _wrap_CoordinateTransformation_TransformPoints_osr_09662cf3c15b8b8e(uintptr_t arg1, swig_intgo arg2, swig_voidp arg3, swig_voidp arg4, swig_voidp arg5);
extern uintptr_t _wrap_CreateCoordinateTransformation_osr_09662cf3c15b8b8e(uintptr_t arg1, uintptr_t arg2);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0))
}

func _swig_getSRS_WKT_WGS84() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_SRS_WKT_WGS84_osr_09662cf3c15b8b8e()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

var SRS_WKT_WGS84 string = _swig_getSRS_WKT_WGS84()
const SRS_PT_ALBERS_CONIC_EQUAL_AREA string = "Albers_Conic_Equal_Area"
const SRS_PT_AZIMUTHAL_EQUIDISTANT string = "Azimuthal_Equidistant"
const SRS_PT_CASSINI_SOLDNER string = "Cassini_Soldner"
const SRS_PT_CYLINDRICAL_EQUAL_AREA string = "Cylindrical_Equal_Area"
const SRS_PT_BONNE string = "Bonne"
const SRS_PT_ECKERT_I string = "Eckert_I"
const SRS_PT_ECKERT_II string = "Eckert_II"
const SRS_PT_ECKERT_III string = "Eckert_III"
const SRS_PT_ECKERT_IV string = "Eckert_IV"
const SRS_PT_ECKERT_V string = "Eckert_V"
const SRS_PT_ECKERT_VI string = "Eckert_VI"
const SRS_PT_EQUIDISTANT_CONIC string = "Equidistant_Conic"
const SRS_PT_EQUIRECTANGULAR string = "Equirectangular"
const SRS_PT_GALL_STEREOGRAPHIC string = "Gall_Stereographic"
const SRS_PT_GAUSSSCHREIBERTMERCATOR string = "Gauss_Schreiber_Transverse_Mercator"
const SRS_PT_GEOSTATIONARY_SATELLITE string = "Geostationary_Satellite"
const SRS_PT_GOODE_HOMOLOSINE string = "Goode_Homolosine"
const SRS_PT_IGH string = "Interrupted_Goode_Homolosine"
const SRS_PT_GNOMONIC string = "Gnomonic"
const SRS_PT_HOTINE_OBLIQUE_MERCATOR_AZIMUTH_CENTER string = "Hotine_Oblique_Mercator_Azimuth_Center"
const SRS_PT_HOTINE_OBLIQUE_MERCATOR string = "Hotine_Oblique_Mercator"
const SRS_PT_HOTINE_OBLIQUE_MERCATOR_TWO_POINT_NATURAL_ORIGIN string = "Hotine_Oblique_Mercator_Two_Point_Natural_Origin"
const SRS_PT_LABORDE_OBLIQUE_MERCATOR string = "Laborde_Oblique_Mercator"
const SRS_PT_LAMBERT_CONFORMAL_CONIC_1SP string = "Lambert_Conformal_Conic_1SP"
const SRS_PT_LAMBERT_CONFORMAL_CONIC_2SP string = "Lambert_Conformal_Conic_2SP"
const SRS_PT_LAMBERT_CONFORMAL_CONIC_2SP_BELGIUM string = "Lambert_Conformal_Conic_2SP_Belgium"
const SRS_PT_LAMBERT_AZIMUTHAL_EQUAL_AREA string = "Lambert_Azimuthal_Equal_Area"
const SRS_PT_MERCATOR_1SP string = "Mercator_1SP"
const SRS_PT_MERCATOR_2SP string = "Mercator_2SP"
const SRS_PT_MERCATOR_AUXILIARY_SPHERE string = "Mercator_Auxiliary_Sphere"
const SRS_PT_MILLER_CYLINDRICAL string = "Miller_Cylindrical"
const SRS_PT_MOLLWEIDE string = "Mollweide"
const SRS_PT_NEW_ZEALAND_MAP_GRID string = "New_Zealand_Map_Grid"
const SRS_PT_OBLIQUE_STEREOGRAPHIC string = "Oblique_Stereographic"
const SRS_PT_ORTHOGRAPHIC string = "Orthographic"
const SRS_PT_POLAR_STEREOGRAPHIC string = "Polar_Stereographic"
const SRS_PT_POLYCONIC string = "Polyconic"
const SRS_PT_ROBINSON string = "Robinson"
const SRS_PT_SINUSOIDAL string = "Sinusoidal"
const SRS_PT_STEREOGRAPHIC string = "Stereographic"
const SRS_PT_SWISS_OBLIQUE_CYLINDRICAL string = "Swiss_Oblique_Cylindrical"
const SRS_PT_TRANSVERSE_MERCATOR string = "Transverse_Mercator"
const SRS_PT_TRANSVERSE_MERCATOR_SOUTH_ORIENTED string = "Transverse_Mercator_South_Orientated"
const SRS_PT_TRANSVERSE_MERCATOR_MI_21 string = "Transverse_Mercator_MapInfo_21"
const SRS_PT_TRANSVERSE_MERCATOR_MI_22 string = "Transverse_Mercator_MapInfo_22"
const SRS_PT_TRANSVERSE_MERCATOR_MI_23 string = "Transverse_Mercator_MapInfo_23"
const SRS_PT_TRANSVERSE_MERCATOR_MI_24 string = "Transverse_Mercator_MapInfo_24"
const SRS_PT_TRANSVERSE_MERCATOR_MI_25 string = "Transverse_Mercator_MapInfo_25"
const SRS_PT_TUNISIA_MINING_GRID string = "Tunisia_Mining_Grid"
const SRS_PT_TWO_POINT_EQUIDISTANT string = "Two_Point_Equidistant"
const SRS_PT_VANDERGRINTEN string = "VanDerGrinten"
const SRS_PT_KROVAK string = "Krovak"
const SRS_PT_IMW_POLYCONIC string = "International_Map_of_the_World_Polyconic"
const SRS_PT_WAGNER_I string = "Wagner_I"
const SRS_PT_WAGNER_II string = "Wagner_II"
const SRS_PT_WAGNER_III string = "Wagner_III"
const SRS_PT_WAGNER_IV string = "Wagner_IV"
const SRS_PT_WAGNER_V string = "Wagner_V"
const SRS_PT_WAGNER_VI string = "Wagner_VI"
const SRS_PT_WAGNER_VII string = "Wagner_VII"
const SRS_PT_QSC string = "Quadrilateralized_Spherical_Cube"
const SRS_PT_AITOFF string = "Aitoff"
const SRS_PT_WINKEL_I string = "Winkel_I"
const SRS_PT_WINKEL_II string = "Winkel_II"
const SRS_PT_WINKEL_TRIPEL string = "Winkel_Tripel"
const SRS_PT_CRASTER_PARABOLIC string = "Craster_Parabolic"
const SRS_PT_LOXIMUTHAL string = "Loximuthal"
const SRS_PT_QUARTIC_AUTHALIC string = "Quartic_Authalic"
const SRS_PT_SCH string = "Spherical_Cross_Track_Height"
const SRS_PP_CENTRAL_MERIDIAN string = "central_meridian"
const SRS_PP_SCALE_FACTOR string = "scale_factor"
const SRS_PP_STANDARD_PARALLEL_1 string = "standard_parallel_1"
const SRS_PP_STANDARD_PARALLEL_2 string = "standard_parallel_2"
const SRS_PP_PSEUDO_STD_PARALLEL_1 string = "pseudo_standard_parallel_1"
const SRS_PP_LONGITUDE_OF_CENTER string = "longitude_of_center"
const SRS_PP_LATITUDE_OF_CENTER string = "latitude_of_center"
const SRS_PP_LONGITUDE_OF_ORIGIN string = "longitude_of_origin"
const SRS_PP_LATITUDE_OF_ORIGIN string = "latitude_of_origin"
const SRS_PP_FALSE_EASTING string = "false_easting"
const SRS_PP_FALSE_NORTHING string = "false_northing"
const SRS_PP_AZIMUTH string = "azimuth"
const SRS_PP_LONGITUDE_OF_POINT_1 string = "longitude_of_point_1"
const SRS_PP_LATITUDE_OF_POINT_1 string = "latitude_of_point_1"
const SRS_PP_LONGITUDE_OF_POINT_2 string = "longitude_of_point_2"
const SRS_PP_LATITUDE_OF_POINT_2 string = "latitude_of_point_2"
const SRS_PP_LONGITUDE_OF_POINT_3 string = "longitude_of_point_3"
const SRS_PP_LATITUDE_OF_POINT_3 string = "latitude_of_point_3"
const SRS_PP_RECTIFIED_GRID_ANGLE string = "rectified_grid_angle"
const SRS_PP_LANDSAT_NUMBER string = "landsat_number"
const SRS_PP_PATH_NUMBER string = "path_number"
const SRS_PP_PERSPECTIVE_POINT_HEIGHT string = "perspective_point_height"
const SRS_PP_SATELLITE_HEIGHT string = "satellite_height"
const SRS_PP_FIPSZONE string = "fipszone"
const SRS_PP_ZONE string = "zone"
const SRS_PP_LATITUDE_OF_1ST_POINT string = "Latitude_Of_1st_Point"
const SRS_PP_LONGITUDE_OF_1ST_POINT string = "Longitude_Of_1st_Point"
const SRS_PP_LATITUDE_OF_2ND_POINT string = "Latitude_Of_2nd_Point"
const SRS_PP_LONGITUDE_OF_2ND_POINT string = "Longitude_Of_2nd_Point"
const SRS_PP_PEG_POINT_LATITUDE string = "peg_point_latitude"
const SRS_PP_PEG_POINT_LONGITUDE string = "peg_point_longitude"
const SRS_PP_PEG_POINT_HEADING string = "peg_point_heading"
const SRS_PP_PEG_POINT_HEIGHT string = "peg_point_height"
const SRS_UL_METER string = "Meter"
const SRS_UL_FOOT string = "Foot (International)"
const SRS_UL_FOOT_CONV string = "0.3048"
const SRS_UL_US_FOOT string = "Foot_US"
const SRS_UL_US_FOOT_CONV string = "0.3048006096012192"
const SRS_UL_NAUTICAL_MILE string = "Nautical Mile"
const SRS_UL_NAUTICAL_MILE_CONV string = "1852.0"
const SRS_UL_LINK string = "Link"
const SRS_UL_LINK_CONV string = "0.20116684023368047"
const SRS_UL_CHAIN string = "Chain"
const SRS_UL_CHAIN_CONV string = "20.116684023368047"
const SRS_UL_ROD string = "Rod"
const SRS_UL_ROD_CONV string = "5.02921005842012"
const SRS_UL_LINK_Clarke string = "Link_Clarke"
const SRS_UL_LINK_Clarke_CONV string = "0.2011661949"
const SRS_UL_KILOMETER string = "Kilometer"
const SRS_UL_KILOMETER_CONV string = "1000."
const SRS_UL_DECIMETER string = "Decimeter"
const SRS_UL_DECIMETER_CONV string = "0.1"
const SRS_UL_CENTIMETER string = "Centimeter"
const SRS_UL_CENTIMETER_CONV string = "0.01"
const SRS_UL_MILLIMETER string = "Millimeter"
const SRS_UL_MILLIMETER_CONV string = "0.001"
const SRS_UL_INTL_NAUT_MILE string = "Nautical_Mile_International"
const SRS_UL_INTL_NAUT_MILE_CONV string = "1852.0"
const SRS_UL_INTL_INCH string = "Inch_International"
const SRS_UL_INTL_INCH_CONV string = "0.0254"
const SRS_UL_INTL_FOOT string = "Foot_International"
const SRS_UL_INTL_FOOT_CONV string = "0.3048"
const SRS_UL_INTL_YARD string = "Yard_International"
const SRS_UL_INTL_YARD_CONV string = "0.9144"
const SRS_UL_INTL_STAT_MILE string = "Statute_Mile_International"
const SRS_UL_INTL_STAT_MILE_CONV string = "1609.344"
const SRS_UL_INTL_FATHOM string = "Fathom_International"
const SRS_UL_INTL_FATHOM_CONV string = "1.8288"
const SRS_UL_INTL_CHAIN string = "Chain_International"
const SRS_UL_INTL_CHAIN_CONV string = "20.1168"
const SRS_UL_INTL_LINK string = "Link_International"
const SRS_UL_INTL_LINK_CONV string = "0.201168"
const SRS_UL_US_INCH string = "Inch_US_Surveyor"
const SRS_UL_US_INCH_CONV string = "0.025400050800101603"
const SRS_UL_US_YARD string = "Yard_US_Surveyor"
const SRS_UL_US_YARD_CONV string = "0.914401828803658"
const SRS_UL_US_CHAIN string = "Chain_US_Surveyor"
const SRS_UL_US_CHAIN_CONV string = "20.11684023368047"
const SRS_UL_US_STAT_MILE string = "Statute_Mile_US_Surveyor"
const SRS_UL_US_STAT_MILE_CONV string = "1609.347218694437"
const SRS_UL_INDIAN_YARD string = "Yard_Indian"
const SRS_UL_INDIAN_YARD_CONV string = "0.91439523"
const SRS_UL_INDIAN_FOOT string = "Foot_Indian"
const SRS_UL_INDIAN_FOOT_CONV string = "0.30479841"
const SRS_UL_INDIAN_CHAIN string = "Chain_Indian"
const SRS_UL_INDIAN_CHAIN_CONV string = "20.11669506"
const SRS_UA_DEGREE string = "degree"
const SRS_UA_DEGREE_CONV string = "0.0174532925199433"
const SRS_UA_RADIAN string = "radian"
const SRS_PM_GREENWICH string = "Greenwich"
const SRS_DN_NAD27 string = "North_American_Datum_1927"
const SRS_DN_NAD83 string = "North_American_Datum_1983"
const SRS_DN_WGS72 string = "WGS_1972"
const SRS_DN_WGS84 string = "WGS_1984"
const SRS_WGS84_SEMIMAJOR float64 = 6378137.0
const SRS_WGS84_INVFLATTENING float64 = 298.257223563
func GetWellKnownGeogCSAsWKT(arg1 string, arg2 *string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_GetWellKnownGeogCSAsWKT_osr_09662cf3c15b8b8e(*(*C.swig_type_2)(unsafe.Pointer(&_swig_i_0)), C.swig_voidp(_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func GetUserInputAsWKT(arg1 string, arg2 *string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_GetUserInputAsWKT_osr_09662cf3c15b8b8e(*(*C.swig_type_3)(unsafe.Pointer(&_swig_i_0)), C.swig_voidp(_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func GetProjectionMethods() (_swig_ret *string) {
	var swig_r *string
	swig_r = (*string)(C._wrap_GetProjectionMethods_osr_09662cf3c15b8b8e())
	return swig_r
}

func GetProjectionMethodParameterList(arg1 string, arg2 *string) (_swig_ret *string) {
	var swig_r *string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (*string)(C._wrap_GetProjectionMethodParameterList_osr_09662cf3c15b8b8e(*(*C.swig_type_4)(unsafe.Pointer(&_swig_i_0)), C.swig_voidp(_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func GetProjectionMethodParamInfo(arg1 string, arg2 string, arg3 *string, arg4 *string, arg5 *float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	C._wrap_GetProjectionMethodParamInfo_osr_09662cf3c15b8b8e(*(*C.swig_type_5)(unsafe.Pointer(&_swig_i_0)), *(*C.swig_type_6)(unsafe.Pointer(&_swig_i_1)), C.swig_voidp(_swig_i_2), C.swig_voidp(_swig_i_3), C.swig_voidp(_swig_i_4))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

type SwigcptrSpatialReference uintptr

func (p SwigcptrSpatialReference) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSpatialReference) SwigIsSpatialReference() {
}

func NewSpatialReference(_swig_args ...interface{}) (_swig_ret SpatialReference) {
	var arg1 string
	if len(_swig_args) > 0 {
		arg1 = _swig_args[0].(string)
	}
	var swig_r SpatialReference
	_swig_i_0 := arg1
	swig_r = (SpatialReference)(SwigcptrSpatialReference(C._wrap_new_SpatialReference_osr_09662cf3c15b8b8e(C.swig_intgo(len(_swig_args)), *(*C.swig_type_7)(unsafe.Pointer(&_swig_i_0)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func DeleteSpatialReference(arg1 SpatialReference) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_SpatialReference_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrSpatialReference) X__str__() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_SpatialReference___str___osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrSpatialReference) IsSame(arg2 SpatialReference) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (int)(C._wrap_SpatialReference_IsSame_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) IsSameGeogCS(arg2 SpatialReference) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (int)(C._wrap_SpatialReference_IsSameGeogCS_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) IsSameVertCS(arg2 SpatialReference) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (int)(C._wrap_SpatialReference_IsSameVertCS_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) IsGeographic() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_SpatialReference_IsGeographic_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) IsProjected() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_SpatialReference_IsProjected_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) IsCompound() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_SpatialReference_IsCompound_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) IsGeocentric() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_SpatialReference_IsGeocentric_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) IsLocal() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_SpatialReference_IsLocal_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) IsVertical() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_SpatialReference_IsVertical_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) EPSGTreatsAsLatLong() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_SpatialReference_EPSGTreatsAsLatLong_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) EPSGTreatsAsNorthingEasting() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_SpatialReference_EPSGTreatsAsNorthingEasting_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetAuthority(arg2 string, arg3 string, arg4 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_SpatialReference_SetAuthority_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), *(*C.swig_type_9)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_10)(unsafe.Pointer(&_swig_i_2)), C.swig_intgo(_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func (arg1 SwigcptrSpatialReference) GetAttrValue(arg2 string, _swig_args ...interface{}) (_swig_ret string) {
	var arg3 int
	if len(_swig_args) > 0 {
		arg3 = _swig_args[0].(int)
	}
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r_p := C._wrap_SpatialReference_GetAttrValue_osr_09662cf3c15b8b8e(C.swig_intgo(len(_swig_args)), C.uintptr_t(_swig_i_0), *(*C.swig_type_12)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrSpatialReference) SetAttrValue(arg2 string, arg3 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_SpatialReference_SetAttrValue_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), *(*C.swig_type_13)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_14)(unsafe.Pointer(&_swig_i_2))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetAngularUnits(arg2 string, arg3 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_SpatialReference_SetAngularUnits_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), *(*C.swig_type_15)(unsafe.Pointer(&_swig_i_1)), C.double(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrSpatialReference) GetAngularUnits() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_SpatialReference_GetAngularUnits_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetTargetLinearUnits(arg2 string, arg3 string, arg4 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_SpatialReference_SetTargetLinearUnits_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), *(*C.swig_type_16)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_17)(unsafe.Pointer(&_swig_i_2)), C.double(_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetLinearUnits(arg2 string, arg3 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_SpatialReference_SetLinearUnits_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), *(*C.swig_type_18)(unsafe.Pointer(&_swig_i_1)), C.double(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetLinearUnitsAndUpdateParameters(arg2 string, arg3 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_SpatialReference_SetLinearUnitsAndUpdateParameters_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), *(*C.swig_type_19)(unsafe.Pointer(&_swig_i_1)), C.double(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrSpatialReference) GetLinearUnits() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_SpatialReference_GetLinearUnits_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) GetLinearUnitsName() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_SpatialReference_GetLinearUnitsName_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrSpatialReference) GetAuthorityCode(arg2 string) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r_p := C._wrap_SpatialReference_GetAuthorityCode_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), *(*C.swig_type_22)(unsafe.Pointer(&_swig_i_1)))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrSpatialReference) GetAuthorityName(arg2 string) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r_p := C._wrap_SpatialReference_GetAuthorityName_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), *(*C.swig_type_24)(unsafe.Pointer(&_swig_i_1)))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrSpatialReference) SetUTM(arg2 int, _swig_args ...interface{}) (_swig_ret int) {
	var arg3 int
	if len(_swig_args) > 0 {
		arg3 = _swig_args[0].(int)
	}
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_SpatialReference_SetUTM_osr_09662cf3c15b8b8e(C.swig_intgo(len(_swig_args)), C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) GetUTMZone() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_SpatialReference_GetUTMZone_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetStatePlane(arg2 int, _swig_args ...interface{}) (_swig_ret int) {
	var arg3 int
	if len(_swig_args) > 0 {
		arg3 = _swig_args[0].(int)
	}
	var arg4 string
	if len(_swig_args) > 1 {
		arg4 = _swig_args[1].(string)
	}
	var arg5 float64
	if len(_swig_args) > 2 {
		arg5 = _swig_args[2].(float64)
	}
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (int)(C._wrap_SpatialReference_SetStatePlane_osr_09662cf3c15b8b8e(C.swig_intgo(len(_swig_args)), C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), *(*C.swig_type_25)(unsafe.Pointer(&_swig_i_3)), C.double(_swig_i_4)))
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
	return swig_r
}

func (arg1 SwigcptrSpatialReference) AutoIdentifyEPSG() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_SpatialReference_AutoIdentifyEPSG_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetProjection(arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_SpatialReference_SetProjection_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), *(*C.swig_type_26)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetProjParm(arg2 string, arg3 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_SpatialReference_SetProjParm_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), *(*C.swig_type_27)(unsafe.Pointer(&_swig_i_1)), C.double(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrSpatialReference) GetProjParm(arg2 string, _swig_args ...interface{}) (_swig_ret float64) {
	var arg3 float64
	if len(_swig_args) > 0 {
		arg3 = _swig_args[0].(float64)
	}
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (float64)(C._wrap_SpatialReference_GetProjParm_osr_09662cf3c15b8b8e(C.swig_intgo(len(_swig_args)), C.uintptr_t(_swig_i_0), *(*C.swig_type_28)(unsafe.Pointer(&_swig_i_1)), C.double(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetNormProjParm(arg2 string, arg3 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_SpatialReference_SetNormProjParm_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), *(*C.swig_type_29)(unsafe.Pointer(&_swig_i_1)), C.double(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrSpatialReference) GetNormProjParm(arg2 string, _swig_args ...interface{}) (_swig_ret float64) {
	var arg3 float64
	if len(_swig_args) > 0 {
		arg3 = _swig_args[0].(float64)
	}
	var swig_r float64
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (float64)(C._wrap_SpatialReference_GetNormProjParm_osr_09662cf3c15b8b8e(C.swig_intgo(len(_swig_args)), C.uintptr_t(_swig_i_0), *(*C.swig_type_30)(unsafe.Pointer(&_swig_i_1)), C.double(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrSpatialReference) GetSemiMajor() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_SpatialReference_GetSemiMajor_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) GetSemiMinor() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_SpatialReference_GetSemiMinor_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) GetInvFlattening() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_SpatialReference_GetInvFlattening_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetACEA(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64, arg7 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	swig_r = (int)(C._wrap_SpatialReference_SetACEA_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4), C.double(_swig_i_5), C.double(_swig_i_6)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetAE(arg2 float64, arg3 float64, arg4 float64, arg5 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (int)(C._wrap_SpatialReference_SetAE_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetBonne(arg2 float64, arg3 float64, arg4 float64, arg5 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (int)(C._wrap_SpatialReference_SetBonne_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetCEA(arg2 float64, arg3 float64, arg4 float64, arg5 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (int)(C._wrap_SpatialReference_SetCEA_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetCS(arg2 float64, arg3 float64, arg4 float64, arg5 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (int)(C._wrap_SpatialReference_SetCS_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetEC(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64, arg7 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	swig_r = (int)(C._wrap_SpatialReference_SetEC_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4), C.double(_swig_i_5), C.double(_swig_i_6)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetEckertIV(arg2 float64, arg3 float64, arg4 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_SpatialReference_SetEckertIV_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetEckertVI(arg2 float64, arg3 float64, arg4 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_SpatialReference_SetEckertVI_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetEquirectangular(arg2 float64, arg3 float64, arg4 float64, arg5 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (int)(C._wrap_SpatialReference_SetEquirectangular_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetEquirectangular2(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	swig_r = (int)(C._wrap_SpatialReference_SetEquirectangular2_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4), C.double(_swig_i_5)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetGaussSchreiberTMercator(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	swig_r = (int)(C._wrap_SpatialReference_SetGaussSchreiberTMercator_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4), C.double(_swig_i_5)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetGS(arg2 float64, arg3 float64, arg4 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_SpatialReference_SetGS_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetGH(arg2 float64, arg3 float64, arg4 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_SpatialReference_SetGH_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetIGH() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_SpatialReference_SetIGH_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetGEOS(arg2 float64, arg3 float64, arg4 float64, arg5 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (int)(C._wrap_SpatialReference_SetGEOS_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetGnomonic(arg2 float64, arg3 float64, arg4 float64, arg5 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (int)(C._wrap_SpatialReference_SetGnomonic_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetHOM(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64, arg7 float64, arg8 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	swig_r = (int)(C._wrap_SpatialReference_SetHOM_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4), C.double(_swig_i_5), C.double(_swig_i_6), C.double(_swig_i_7)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetHOM2PNO(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64, arg7 float64, arg8 float64, arg9 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	_swig_i_8 := arg9
	swig_r = (int)(C._wrap_SpatialReference_SetHOM2PNO_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4), C.double(_swig_i_5), C.double(_swig_i_6), C.double(_swig_i_7), C.double(_swig_i_8)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetKrovak(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64, arg7 float64, arg8 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	swig_r = (int)(C._wrap_SpatialReference_SetKrovak_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4), C.double(_swig_i_5), C.double(_swig_i_6), C.double(_swig_i_7)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetLAEA(arg2 float64, arg3 float64, arg4 float64, arg5 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (int)(C._wrap_SpatialReference_SetLAEA_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetLCC(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64, arg7 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	swig_r = (int)(C._wrap_SpatialReference_SetLCC_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4), C.double(_swig_i_5), C.double(_swig_i_6)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetLCC1SP(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	swig_r = (int)(C._wrap_SpatialReference_SetLCC1SP_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4), C.double(_swig_i_5)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetLCCB(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64, arg7 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	swig_r = (int)(C._wrap_SpatialReference_SetLCCB_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4), C.double(_swig_i_5), C.double(_swig_i_6)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetMC(arg2 float64, arg3 float64, arg4 float64, arg5 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (int)(C._wrap_SpatialReference_SetMC_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetMercator(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	swig_r = (int)(C._wrap_SpatialReference_SetMercator_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4), C.double(_swig_i_5)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetMollweide(arg2 float64, arg3 float64, arg4 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_SpatialReference_SetMollweide_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetNZMG(arg2 float64, arg3 float64, arg4 float64, arg5 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (int)(C._wrap_SpatialReference_SetNZMG_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetOS(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	swig_r = (int)(C._wrap_SpatialReference_SetOS_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4), C.double(_swig_i_5)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetOrthographic(arg2 float64, arg3 float64, arg4 float64, arg5 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (int)(C._wrap_SpatialReference_SetOrthographic_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetPolyconic(arg2 float64, arg3 float64, arg4 float64, arg5 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (int)(C._wrap_SpatialReference_SetPolyconic_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetPS(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	swig_r = (int)(C._wrap_SpatialReference_SetPS_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4), C.double(_swig_i_5)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetRobinson(arg2 float64, arg3 float64, arg4 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_SpatialReference_SetRobinson_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetSinusoidal(arg2 float64, arg3 float64, arg4 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_SpatialReference_SetSinusoidal_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetStereographic(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	swig_r = (int)(C._wrap_SpatialReference_SetStereographic_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4), C.double(_swig_i_5)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetSOC(arg2 float64, arg3 float64, arg4 float64, arg5 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (int)(C._wrap_SpatialReference_SetSOC_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetTM(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	swig_r = (int)(C._wrap_SpatialReference_SetTM_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4), C.double(_swig_i_5)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetTMVariant(arg2 string, arg3 float64, arg4 float64, arg5 float64, arg6 float64, arg7 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	swig_r = (int)(C._wrap_SpatialReference_SetTMVariant_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), *(*C.swig_type_31)(unsafe.Pointer(&_swig_i_1)), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4), C.double(_swig_i_5), C.double(_swig_i_6)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetTMG(arg2 float64, arg3 float64, arg4 float64, arg5 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (int)(C._wrap_SpatialReference_SetTMG_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetTMSO(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	swig_r = (int)(C._wrap_SpatialReference_SetTMSO_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4), C.double(_swig_i_5)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetVDG(arg2 float64, arg3 float64, arg4 float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_SpatialReference_SetVDG_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetWellKnownGeogCS(arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_SpatialReference_SetWellKnownGeogCS_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), *(*C.swig_type_32)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetFromUserInput(arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_SpatialReference_SetFromUserInput_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), *(*C.swig_type_33)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrSpatialReference) CopyGeogCSFrom(arg2 SpatialReference) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (int)(C._wrap_SpatialReference_CopyGeogCSFrom_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetTOWGS84(arg2 float64, arg3 float64, arg4 float64, _swig_args ...interface{}) (_swig_ret int) {
	var arg5 float64
	if len(_swig_args) > 0 {
		arg5 = _swig_args[0].(float64)
	}
	var arg6 float64
	if len(_swig_args) > 1 {
		arg6 = _swig_args[1].(float64)
	}
	var arg7 float64
	if len(_swig_args) > 2 {
		arg7 = _swig_args[2].(float64)
	}
	var arg8 float64
	if len(_swig_args) > 3 {
		arg8 = _swig_args[3].(float64)
	}
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	swig_r = (int)(C._wrap_SpatialReference_SetTOWGS84_osr_09662cf3c15b8b8e(C.swig_intgo(len(_swig_args)), C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4), C.double(_swig_i_5), C.double(_swig_i_6), C.double(_swig_i_7)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) GetTOWGS84(arg2 *float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_SpatialReference_GetTOWGS84_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetLocalCS(arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_SpatialReference_SetLocalCS_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), *(*C.swig_type_34)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetGeogCS(arg2 string, arg3 string, arg4 string, arg5 float64, arg6 float64, _swig_args ...interface{}) (_swig_ret int) {
	var arg7 string
	if len(_swig_args) > 0 {
		arg7 = _swig_args[0].(string)
	}
	var arg8 float64
	if len(_swig_args) > 1 {
		arg8 = _swig_args[1].(float64)
	}
	var arg9 string
	if len(_swig_args) > 2 {
		arg9 = _swig_args[2].(string)
	}
	var arg10 float64
	if len(_swig_args) > 3 {
		arg10 = _swig_args[3].(float64)
	}
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	_swig_i_8 := arg9
	_swig_i_9 := arg10
	swig_r = (int)(C._wrap_SpatialReference_SetGeogCS_osr_09662cf3c15b8b8e(C.swig_intgo(len(_swig_args)), C.uintptr_t(_swig_i_0), *(*C.swig_type_35)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_36)(unsafe.Pointer(&_swig_i_2)), *(*C.swig_type_37)(unsafe.Pointer(&_swig_i_3)), C.double(_swig_i_4), C.double(_swig_i_5), *(*C.swig_type_38)(unsafe.Pointer(&_swig_i_6)), C.double(_swig_i_7), *(*C.swig_type_39)(unsafe.Pointer(&_swig_i_8)), C.double(_swig_i_9)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg7
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg9
	}
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetProjCS(_swig_args ...interface{}) (_swig_ret int) {
	var arg2 string
	if len(_swig_args) > 0 {
		arg2 = _swig_args[0].(string)
	}
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_SpatialReference_SetProjCS_osr_09662cf3c15b8b8e(C.swig_intgo(len(_swig_args)), C.uintptr_t(_swig_i_0), *(*C.swig_type_40)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetGeocCS(_swig_args ...interface{}) (_swig_ret int) {
	var arg2 string
	if len(_swig_args) > 0 {
		arg2 = _swig_args[0].(string)
	}
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_SpatialReference_SetGeocCS_osr_09662cf3c15b8b8e(C.swig_intgo(len(_swig_args)), C.uintptr_t(_swig_i_0), *(*C.swig_type_41)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetVertCS(_swig_args ...interface{}) (_swig_ret int) {
	var arg2 string
	if len(_swig_args) > 0 {
		arg2 = _swig_args[0].(string)
	}
	var arg3 string
	if len(_swig_args) > 1 {
		arg3 = _swig_args[1].(string)
	}
	var arg4 int
	if len(_swig_args) > 2 {
		arg4 = _swig_args[2].(int)
	}
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_SpatialReference_SetVertCS_osr_09662cf3c15b8b8e(C.swig_intgo(len(_swig_args)), C.uintptr_t(_swig_i_0), *(*C.swig_type_42)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_43)(unsafe.Pointer(&_swig_i_2)), C.swig_intgo(_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func (arg1 SwigcptrSpatialReference) SetCompoundCS(arg2 string, arg3 SpatialReference, arg4 SpatialReference) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4.Swigcptr()
	swig_r = (int)(C._wrap_SpatialReference_SetCompoundCS_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), *(*C.swig_type_44)(unsafe.Pointer(&_swig_i_1)), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrSpatialReference) ImportFromWkt(arg2 *string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_SpatialReference_ImportFromWkt_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) ImportFromProj4(arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_SpatialReference_ImportFromProj4_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), *(*C.swig_type_45)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrSpatialReference) ImportFromUrl(arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_SpatialReference_ImportFromUrl_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), *(*C.swig_type_46)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrSpatialReference) ImportFromESRI(arg2 *string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_SpatialReference_ImportFromESRI_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) ImportFromEPSG(arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_SpatialReference_ImportFromEPSG_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) ImportFromEPSGA(arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_SpatialReference_ImportFromEPSGA_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) ImportFromPCI(arg2 string, _swig_args ...interface{}) (_swig_ret int) {
	var arg3 string
	if len(_swig_args) > 0 {
		arg3 = _swig_args[0].(string)
	}
	var arg4 *float64
	if len(_swig_args) > 1 {
		arg4 = _swig_args[1].(*float64)
	}
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_SpatialReference_ImportFromPCI_osr_09662cf3c15b8b8e(C.swig_intgo(len(_swig_args)), C.uintptr_t(_swig_i_0), *(*C.swig_type_47)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_48)(unsafe.Pointer(&_swig_i_2)), C.swig_voidp(_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func (arg1 SwigcptrSpatialReference) ImportFromUSGS(arg2 int64, _swig_args ...interface{}) (_swig_ret int) {
	var arg3 int64
	if len(_swig_args) > 0 {
		arg3 = _swig_args[0].(int64)
	}
	var arg4 *float64
	if len(_swig_args) > 1 {
		arg4 = _swig_args[1].(*float64)
	}
	var arg5 int64
	if len(_swig_args) > 2 {
		arg5 = _swig_args[2].(int64)
	}
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (int)(C._wrap_SpatialReference_ImportFromUSGS_osr_09662cf3c15b8b8e(C.swig_intgo(len(_swig_args)), C.uintptr_t(_swig_i_0), C.swig_type_49(_swig_i_1), C.swig_type_50(_swig_i_2), C.swig_voidp(_swig_i_3), C.swig_type_51(_swig_i_4)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) ImportFromXML(arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_SpatialReference_ImportFromXML_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), *(*C.swig_type_52)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrSpatialReference) ImportFromERM(arg2 string, arg3 string, arg4 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_SpatialReference_ImportFromERM_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), *(*C.swig_type_53)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_54)(unsafe.Pointer(&_swig_i_2)), *(*C.swig_type_55)(unsafe.Pointer(&_swig_i_3))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
	return swig_r
}

func (arg1 SwigcptrSpatialReference) ImportFromMICoordSys(arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_SpatialReference_ImportFromMICoordSys_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), *(*C.swig_type_56)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func (arg1 SwigcptrSpatialReference) ImportFromOzi(arg2 *string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_SpatialReference_ImportFromOzi_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) ExportToWkt(arg2 *string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_SpatialReference_ExportToWkt_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) ExportToPrettyWkt(arg2 *string, _swig_args ...interface{}) (_swig_ret int) {
	var arg3 int
	if len(_swig_args) > 0 {
		arg3 = _swig_args[0].(int)
	}
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_SpatialReference_ExportToPrettyWkt_osr_09662cf3c15b8b8e(C.swig_intgo(len(_swig_args)), C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) ExportToProj4(arg2 *string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_SpatialReference_ExportToProj4_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) ExportToPCI(arg2 *string, arg3 *string, arg4 **float64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_SpatialReference_ExportToPCI_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_voidp(_swig_i_2), C.swig_voidp(_swig_i_3)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) ExportToUSGS(arg2 *int64, arg3 *int64, arg4 **float64, arg5 *int64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (int)(C._wrap_SpatialReference_ExportToUSGS_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_voidp(_swig_i_2), C.swig_voidp(_swig_i_3), C.swig_voidp(_swig_i_4)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) ExportToXML(arg2 *string, _swig_args ...interface{}) (_swig_ret int) {
	var arg3 string
	if len(_swig_args) > 0 {
		arg3 = _swig_args[0].(string)
	}
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_SpatialReference_ExportToXML_osr_09662cf3c15b8b8e(C.swig_intgo(len(_swig_args)), C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), *(*C.swig_type_57)(unsafe.Pointer(&_swig_i_2))))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func (arg1 SwigcptrSpatialReference) ExportToMICoordSys(arg2 *string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_SpatialReference_ExportToMICoordSys_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) CloneGeogCS() (_swig_ret SpatialReference) {
	var swig_r SpatialReference
	_swig_i_0 := arg1
	swig_r = (SpatialReference)(SwigcptrSpatialReference(C._wrap_SpatialReference_CloneGeogCS_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) Clone() (_swig_ret SpatialReference) {
	var swig_r SpatialReference
	_swig_i_0 := arg1
	swig_r = (SpatialReference)(SwigcptrSpatialReference(C._wrap_SpatialReference_Clone_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) Validate() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_SpatialReference_Validate_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) StripCTParms() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_SpatialReference_StripCTParms_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) FixupOrdering() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_SpatialReference_FixupOrdering_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) Fixup() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_SpatialReference_Fixup_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) MorphToESRI() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_SpatialReference_MorphToESRI_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSpatialReference) MorphFromESRI() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_SpatialReference_MorphFromESRI_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0)))
	return swig_r
}

type SpatialReference interface {
	Swigcptr() uintptr
	SwigIsSpatialReference()
	X__str__() (_swig_ret string)
	IsSame(arg2 SpatialReference) (_swig_ret int)
	IsSameGeogCS(arg2 SpatialReference) (_swig_ret int)
	IsSameVertCS(arg2 SpatialReference) (_swig_ret int)
	IsGeographic() (_swig_ret int)
	IsProjected() (_swig_ret int)
	IsCompound() (_swig_ret int)
	IsGeocentric() (_swig_ret int)
	IsLocal() (_swig_ret int)
	IsVertical() (_swig_ret int)
	EPSGTreatsAsLatLong() (_swig_ret int)
	EPSGTreatsAsNorthingEasting() (_swig_ret int)
	SetAuthority(arg2 string, arg3 string, arg4 int) (_swig_ret int)
	GetAttrValue(arg2 string, _swig_args ...interface{}) (_swig_ret string)
	SetAttrValue(arg2 string, arg3 string) (_swig_ret int)
	SetAngularUnits(arg2 string, arg3 float64) (_swig_ret int)
	GetAngularUnits() (_swig_ret float64)
	SetTargetLinearUnits(arg2 string, arg3 string, arg4 float64) (_swig_ret int)
	SetLinearUnits(arg2 string, arg3 float64) (_swig_ret int)
	SetLinearUnitsAndUpdateParameters(arg2 string, arg3 float64) (_swig_ret int)
	GetLinearUnits() (_swig_ret float64)
	GetLinearUnitsName() (_swig_ret string)
	GetAuthorityCode(arg2 string) (_swig_ret string)
	GetAuthorityName(arg2 string) (_swig_ret string)
	SetUTM(arg2 int, _swig_args ...interface{}) (_swig_ret int)
	GetUTMZone() (_swig_ret int)
	SetStatePlane(arg2 int, _swig_args ...interface{}) (_swig_ret int)
	AutoIdentifyEPSG() (_swig_ret int)
	SetProjection(arg2 string) (_swig_ret int)
	SetProjParm(arg2 string, arg3 float64) (_swig_ret int)
	GetProjParm(arg2 string, _swig_args ...interface{}) (_swig_ret float64)
	SetNormProjParm(arg2 string, arg3 float64) (_swig_ret int)
	GetNormProjParm(arg2 string, _swig_args ...interface{}) (_swig_ret float64)
	GetSemiMajor() (_swig_ret float64)
	GetSemiMinor() (_swig_ret float64)
	GetInvFlattening() (_swig_ret float64)
	SetACEA(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64, arg7 float64) (_swig_ret int)
	SetAE(arg2 float64, arg3 float64, arg4 float64, arg5 float64) (_swig_ret int)
	SetBonne(arg2 float64, arg3 float64, arg4 float64, arg5 float64) (_swig_ret int)
	SetCEA(arg2 float64, arg3 float64, arg4 float64, arg5 float64) (_swig_ret int)
	SetCS(arg2 float64, arg3 float64, arg4 float64, arg5 float64) (_swig_ret int)
	SetEC(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64, arg7 float64) (_swig_ret int)
	SetEckertIV(arg2 float64, arg3 float64, arg4 float64) (_swig_ret int)
	SetEckertVI(arg2 float64, arg3 float64, arg4 float64) (_swig_ret int)
	SetEquirectangular(arg2 float64, arg3 float64, arg4 float64, arg5 float64) (_swig_ret int)
	SetEquirectangular2(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64) (_swig_ret int)
	SetGaussSchreiberTMercator(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64) (_swig_ret int)
	SetGS(arg2 float64, arg3 float64, arg4 float64) (_swig_ret int)
	SetGH(arg2 float64, arg3 float64, arg4 float64) (_swig_ret int)
	SetIGH() (_swig_ret int)
	SetGEOS(arg2 float64, arg3 float64, arg4 float64, arg5 float64) (_swig_ret int)
	SetGnomonic(arg2 float64, arg3 float64, arg4 float64, arg5 float64) (_swig_ret int)
	SetHOM(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64, arg7 float64, arg8 float64) (_swig_ret int)
	SetHOM2PNO(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64, arg7 float64, arg8 float64, arg9 float64) (_swig_ret int)
	SetKrovak(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64, arg7 float64, arg8 float64) (_swig_ret int)
	SetLAEA(arg2 float64, arg3 float64, arg4 float64, arg5 float64) (_swig_ret int)
	SetLCC(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64, arg7 float64) (_swig_ret int)
	SetLCC1SP(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64) (_swig_ret int)
	SetLCCB(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64, arg7 float64) (_swig_ret int)
	SetMC(arg2 float64, arg3 float64, arg4 float64, arg5 float64) (_swig_ret int)
	SetMercator(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64) (_swig_ret int)
	SetMollweide(arg2 float64, arg3 float64, arg4 float64) (_swig_ret int)
	SetNZMG(arg2 float64, arg3 float64, arg4 float64, arg5 float64) (_swig_ret int)
	SetOS(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64) (_swig_ret int)
	SetOrthographic(arg2 float64, arg3 float64, arg4 float64, arg5 float64) (_swig_ret int)
	SetPolyconic(arg2 float64, arg3 float64, arg4 float64, arg5 float64) (_swig_ret int)
	SetPS(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64) (_swig_ret int)
	SetRobinson(arg2 float64, arg3 float64, arg4 float64) (_swig_ret int)
	SetSinusoidal(arg2 float64, arg3 float64, arg4 float64) (_swig_ret int)
	SetStereographic(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64) (_swig_ret int)
	SetSOC(arg2 float64, arg3 float64, arg4 float64, arg5 float64) (_swig_ret int)
	SetTM(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64) (_swig_ret int)
	SetTMVariant(arg2 string, arg3 float64, arg4 float64, arg5 float64, arg6 float64, arg7 float64) (_swig_ret int)
	SetTMG(arg2 float64, arg3 float64, arg4 float64, arg5 float64) (_swig_ret int)
	SetTMSO(arg2 float64, arg3 float64, arg4 float64, arg5 float64, arg6 float64) (_swig_ret int)
	SetVDG(arg2 float64, arg3 float64, arg4 float64) (_swig_ret int)
	SetWellKnownGeogCS(arg2 string) (_swig_ret int)
	SetFromUserInput(arg2 string) (_swig_ret int)
	CopyGeogCSFrom(arg2 SpatialReference) (_swig_ret int)
	SetTOWGS84(arg2 float64, arg3 float64, arg4 float64, _swig_args ...interface{}) (_swig_ret int)
	GetTOWGS84(arg2 *float64) (_swig_ret int)
	SetLocalCS(arg2 string) (_swig_ret int)
	SetGeogCS(arg2 string, arg3 string, arg4 string, arg5 float64, arg6 float64, _swig_args ...interface{}) (_swig_ret int)
	SetProjCS(_swig_args ...interface{}) (_swig_ret int)
	SetGeocCS(_swig_args ...interface{}) (_swig_ret int)
	SetVertCS(_swig_args ...interface{}) (_swig_ret int)
	SetCompoundCS(arg2 string, arg3 SpatialReference, arg4 SpatialReference) (_swig_ret int)
	ImportFromWkt(arg2 *string) (_swig_ret int)
	ImportFromProj4(arg2 string) (_swig_ret int)
	ImportFromUrl(arg2 string) (_swig_ret int)
	ImportFromESRI(arg2 *string) (_swig_ret int)
	ImportFromEPSG(arg2 int) (_swig_ret int)
	ImportFromEPSGA(arg2 int) (_swig_ret int)
	ImportFromPCI(arg2 string, _swig_args ...interface{}) (_swig_ret int)
	ImportFromUSGS(arg2 int64, _swig_args ...interface{}) (_swig_ret int)
	ImportFromXML(arg2 string) (_swig_ret int)
	ImportFromERM(arg2 string, arg3 string, arg4 string) (_swig_ret int)
	ImportFromMICoordSys(arg2 string) (_swig_ret int)
	ImportFromOzi(arg2 *string) (_swig_ret int)
	ExportToWkt(arg2 *string) (_swig_ret int)
	ExportToPrettyWkt(arg2 *string, _swig_args ...interface{}) (_swig_ret int)
	ExportToProj4(arg2 *string) (_swig_ret int)
	ExportToPCI(arg2 *string, arg3 *string, arg4 **float64) (_swig_ret int)
	ExportToUSGS(arg2 *int64, arg3 *int64, arg4 **float64, arg5 *int64) (_swig_ret int)
	ExportToXML(arg2 *string, _swig_args ...interface{}) (_swig_ret int)
	ExportToMICoordSys(arg2 *string) (_swig_ret int)
	CloneGeogCS() (_swig_ret SpatialReference)
	Clone() (_swig_ret SpatialReference)
	Validate() (_swig_ret int)
	StripCTParms() (_swig_ret int)
	FixupOrdering() (_swig_ret int)
	Fixup() (_swig_ret int)
	MorphToESRI() (_swig_ret int)
	MorphFromESRI() (_swig_ret int)
}

type SwigcptrCoordinateTransformation uintptr

func (p SwigcptrCoordinateTransformation) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrCoordinateTransformation) SwigIsCoordinateTransformation() {
}

func NewCoordinateTransformation(arg1 SpatialReference, arg2 SpatialReference) (_swig_ret CoordinateTransformation) {
	var swig_r CoordinateTransformation
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (CoordinateTransformation)(SwigcptrCoordinateTransformation(C._wrap_new_CoordinateTransformation_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func DeleteCoordinateTransformation(arg1 CoordinateTransformation) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_CoordinateTransformation_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrCoordinateTransformation) TransformPoint__SWIG_0(arg2 *float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_CoordinateTransformation_TransformPoint__SWIG_0_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrCoordinateTransformation) TransformPoint__SWIG_1(arg2 *float64, arg3 float64, arg4 float64, _swig_args ...interface{}) {
	var arg5 float64
	if len(_swig_args) > 0 {
		arg5 = _swig_args[0].(float64)
	}
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	C._wrap_CoordinateTransformation_TransformPoint__SWIG_1_osr_09662cf3c15b8b8e(C.swig_intgo(len(_swig_args)), C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.double(_swig_i_2), C.double(_swig_i_3), C.double(_swig_i_4))
}

func (p SwigcptrCoordinateTransformation) TransformPoint(a ...interface{}) {
	argc := len(a)
	if argc == 1 {
		p.TransformPoint__SWIG_0(a[0].(*float64))
		return
	}
	if argc >= 3 && argc <= 4 {
		switch argc {
		case 3:
			p.TransformPoint__SWIG_1(a[0].(*float64), a[1].(float64), a[2].(float64))
			return
		case 4:
			p.TransformPoint__SWIG_1(a[0].(*float64), a[1].(float64), a[2].(float64), a[3])
			return
		}
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrCoordinateTransformation) TransformPoints(arg2 int, arg3 *float64, arg4 *float64, arg5 *float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	C._wrap_CoordinateTransformation_TransformPoints_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_voidp(_swig_i_2), C.swig_voidp(_swig_i_3), C.swig_voidp(_swig_i_4))
}

type CoordinateTransformation interface {
	Swigcptr() uintptr
	SwigIsCoordinateTransformation()
	TransformPoint(a ...interface{})
	TransformPoints(arg2 int, arg3 *float64, arg4 *float64, arg5 *float64)
}

func CreateCoordinateTransformation(arg1 SpatialReference, arg2 SpatialReference) (_swig_ret CoordinateTransformation) {
	var swig_r CoordinateTransformation
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (CoordinateTransformation)(SwigcptrCoordinateTransformation(C._wrap_CreateCoordinateTransformation_osr_09662cf3c15b8b8e(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}


